import type { ApiEndpoint } from "@/components/docs/ApiTester"

export const apiDocs: ApiEndpoint[] = [
  // {
  //   id: "sessions-list",
  //   title: "List Sessions",
  //   path: "/api/sessions",
  //   method: "GET",
  //   description: "List WAHA sessions (requires user authentication).",
  //   expectedResponse: [{ id: "string", state: "string" }],
  // },
  // {
  //   id: "sessions-create",
  //   title: "Create Session",
  //   path: "/api/sessions",
  //   method: "POST",
  //   description: "Create a WAHA session (requires user authentication).",
  //   sampleBody: { name: "default", engine: "whatsapp-web" },
  //   expectedResponse: { id: "string", state: "string" },
  // },
  // {
  //   id: "sessions-start",
  //   title: "Start Session",
  //   path: "/api/sessions/default/start",
  //   method: "POST",
  //   description: "Start a session (requires user authentication). Replace 'default' with your session id.",
  //   expectedResponse: { ok: true },
  // },
  // {
  //   id: "sessions-stop",
  //   title: "Stop Session",
  //   path: "/api/sessions/default/stop",
  //   method: "POST",
  //   description: "Stop a session (requires user authentication). Replace 'default' with your session id.",
  //   expectedResponse: { ok: true },
  // },
  // {
  //   id: "sessions-qr",
  //   title: "Get Session QR",
  //   path: "/api/sessions/default/qr",
  //   method: "GET",
  //   description: "Get QR code for pairing (requires user authentication). Replace 'default' with your session id.",
  //   expectedResponse: { png: "data:image/png;base64,..." },
  // },
  // {
  //   id: "applications-list",
  //   title: "List Applications",
  //   path: "/api/applications",
  //   method: "GET",
  //   description: "List your applications (requires user authentication).",
  //   expectedResponse: [{ id: "string", name: "string", slug: "string", createdAt: "ISO", updatedAt: "ISO" }],
  // },
  // {
  //   id: "applications-create",
  //   title: "Create Application",
  //   path: "/api/applications",
  //   method: "POST",
  //   description: "Create an application (requires user authentication).",
  //   sampleBody: { name: "My App" },
  //   expectedResponse: { id: "string", name: "string", slug: "string" },
  // },
  // {
  //   id: "keys-list",
  //   title: "List API Keys",
  //   path: "/api/applications/my-app/keys",
  //   method: "GET",
  //   description: "List API keys for an application (requires user authentication). Replace 'my-app' with your app slug.",
  //   expectedResponse: [{ id: "string", prefix: "string", lastFour: "string", enabled: true, createdAt: "ISO" }],
  // },
  // {
  //   id: "keys-create",
  //   title: "Create API Key",
  //   path: "/api/applications/my-app/keys",
  //   method: "POST",
  //   description: "Create an API key for an application (requires user authentication). Replace 'my-app' with your app slug.",
  //   expectedResponse: { id: "string", key: "string", prefix: "string", lastFour: "string", enabled: true, createdAt: "ISO" },
  // },
  {
    id: "send-message",
    title: "Send Message",
    path: "/api/chat/send",
    method: "POST",
    description: "Send a text message via WAHA proxy.",
    sampleBody: { sessionId: "default", to: "12025550123@c.us", text: "Hello" },
    expectedResponse: { id: "string", timestamp: 0, to: "string", body: "string" },
  },
]
